//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.UTIL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServicesPackage", ConfigurationName="UTIL.ServicesPortType")]
    public interface ServicesPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getBalances", ReplyAction="urn:getBalancesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApp1.UTIL.getBalancesResponse getBalances(WpfApp1.UTIL.getBalancesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getBalances", ReplyAction="urn:getBalancesResponse")]
        System.Threading.Tasks.Task<WpfApp1.UTIL.getBalancesResponse> getBalancesAsync(WpfApp1.UTIL.getBalancesRequest request);
        
        // CODEGEN: Parameter 'inputFirstName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:createAccount", ReplyAction="urn:createAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApp1.UTIL.createAccountResponse createAccount(WpfApp1.UTIL.createAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:createAccount", ReplyAction="urn:createAccountResponse")]
        System.Threading.Tasks.Task<WpfApp1.UTIL.createAccountResponse> createAccountAsync(WpfApp1.UTIL.createAccountRequest request);
        
        // CODEGEN: Parameter 'inputPhoneNumber' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:login", ReplyAction="urn:loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApp1.UTIL.loginResponse login(WpfApp1.UTIL.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:login", ReplyAction="urn:loginResponse")]
        System.Threading.Tasks.Task<WpfApp1.UTIL.loginResponse> loginAsync(WpfApp1.UTIL.loginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:showProfile", ReplyAction="urn:showProfileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApp1.UTIL.showProfileResponse showProfile(WpfApp1.UTIL.showProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:showProfile", ReplyAction="urn:showProfileResponse")]
        System.Threading.Tasks.Task<WpfApp1.UTIL.showProfileResponse> showProfileAsync(WpfApp1.UTIL.showProfileRequest request);
        
        // CODEGEN: Parameter 'inputPhoneNumber' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:changePassword", ReplyAction="urn:changePasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApp1.UTIL.changePasswordResponse changePassword(WpfApp1.UTIL.changePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:changePassword", ReplyAction="urn:changePasswordResponse")]
        System.Threading.Tasks.Task<WpfApp1.UTIL.changePasswordResponse> changePasswordAsync(WpfApp1.UTIL.changePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalances", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class getBalancesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPhoneNumber;
        
        public getBalancesRequest() {
        }
        
        public getBalancesRequest(string inputPhoneNumber) {
            this.inputPhoneNumber = inputPhoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalancesResponse", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class getBalancesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public double[] @return;
        
        public getBalancesResponse() {
        }
        
        public getBalancesResponse(double[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAccount", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class createAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputFirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputLastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputBirthDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputTcNumber;
        
        public createAccountRequest() {
        }
        
        public createAccountRequest(string inputFirstName, string inputLastName, string inputPhoneNumber, string inputEmail, string inputPassword, string inputBirthDate, string inputTcNumber) {
            this.inputFirstName = inputFirstName;
            this.inputLastName = inputLastName;
            this.inputPhoneNumber = inputPhoneNumber;
            this.inputEmail = inputEmail;
            this.inputPassword = inputPassword;
            this.inputBirthDate = inputBirthDate;
            this.inputTcNumber = inputTcNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAccountResponse", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class createAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        public int @return;
        
        public createAccountResponse() {
        }
        
        public createAccountResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPassword;
        
        public loginRequest() {
        }
        
        public loginRequest(string inputPhoneNumber, string inputPassword) {
            this.inputPhoneNumber = inputPhoneNumber;
            this.inputPassword = inputPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        public int @return;
        
        public loginResponse() {
        }
        
        public loginResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="showProfile", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class showProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPhoneNumber;
        
        public showProfileRequest() {
        }
        
        public showProfileRequest(string inputPhoneNumber) {
            this.inputPhoneNumber = inputPhoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="showProfileResponse", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class showProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public showProfileResponse() {
        }
        
        public showProfileResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePassword", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputPhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputTcNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inputNewPassword;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(string inputPhoneNumber, string inputTcNumber, string inputNewPassword) {
            this.inputPhoneNumber = inputPhoneNumber;
            this.inputTcNumber = inputTcNumber;
            this.inputNewPassword = inputNewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordResponse", WrapperNamespace="http://ServicesPackage", IsWrapped=true)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicesPackage", Order=0)]
        public int @return;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesPortTypeChannel : WpfApp1.UTIL.ServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesPortTypeClient : System.ServiceModel.ClientBase<WpfApp1.UTIL.ServicesPortType>, WpfApp1.UTIL.ServicesPortType {
        
        public ServicesPortTypeClient() {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.UTIL.getBalancesResponse WpfApp1.UTIL.ServicesPortType.getBalances(WpfApp1.UTIL.getBalancesRequest request) {
            return base.Channel.getBalances(request);
        }
        
        public double[] getBalances(string inputPhoneNumber) {
            WpfApp1.UTIL.getBalancesRequest inValue = new WpfApp1.UTIL.getBalancesRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            WpfApp1.UTIL.getBalancesResponse retVal = ((WpfApp1.UTIL.ServicesPortType)(this)).getBalances(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.UTIL.getBalancesResponse> WpfApp1.UTIL.ServicesPortType.getBalancesAsync(WpfApp1.UTIL.getBalancesRequest request) {
            return base.Channel.getBalancesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.UTIL.getBalancesResponse> getBalancesAsync(string inputPhoneNumber) {
            WpfApp1.UTIL.getBalancesRequest inValue = new WpfApp1.UTIL.getBalancesRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            return ((WpfApp1.UTIL.ServicesPortType)(this)).getBalancesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.UTIL.createAccountResponse WpfApp1.UTIL.ServicesPortType.createAccount(WpfApp1.UTIL.createAccountRequest request) {
            return base.Channel.createAccount(request);
        }
        
        public int createAccount(string inputFirstName, string inputLastName, string inputPhoneNumber, string inputEmail, string inputPassword, string inputBirthDate, string inputTcNumber) {
            WpfApp1.UTIL.createAccountRequest inValue = new WpfApp1.UTIL.createAccountRequest();
            inValue.inputFirstName = inputFirstName;
            inValue.inputLastName = inputLastName;
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputEmail = inputEmail;
            inValue.inputPassword = inputPassword;
            inValue.inputBirthDate = inputBirthDate;
            inValue.inputTcNumber = inputTcNumber;
            WpfApp1.UTIL.createAccountResponse retVal = ((WpfApp1.UTIL.ServicesPortType)(this)).createAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.UTIL.createAccountResponse> WpfApp1.UTIL.ServicesPortType.createAccountAsync(WpfApp1.UTIL.createAccountRequest request) {
            return base.Channel.createAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.UTIL.createAccountResponse> createAccountAsync(string inputFirstName, string inputLastName, string inputPhoneNumber, string inputEmail, string inputPassword, string inputBirthDate, string inputTcNumber) {
            WpfApp1.UTIL.createAccountRequest inValue = new WpfApp1.UTIL.createAccountRequest();
            inValue.inputFirstName = inputFirstName;
            inValue.inputLastName = inputLastName;
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputEmail = inputEmail;
            inValue.inputPassword = inputPassword;
            inValue.inputBirthDate = inputBirthDate;
            inValue.inputTcNumber = inputTcNumber;
            return ((WpfApp1.UTIL.ServicesPortType)(this)).createAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.UTIL.loginResponse WpfApp1.UTIL.ServicesPortType.login(WpfApp1.UTIL.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public int login(string inputPhoneNumber, string inputPassword) {
            WpfApp1.UTIL.loginRequest inValue = new WpfApp1.UTIL.loginRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputPassword = inputPassword;
            WpfApp1.UTIL.loginResponse retVal = ((WpfApp1.UTIL.ServicesPortType)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.UTIL.loginResponse> WpfApp1.UTIL.ServicesPortType.loginAsync(WpfApp1.UTIL.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.UTIL.loginResponse> loginAsync(string inputPhoneNumber, string inputPassword) {
            WpfApp1.UTIL.loginRequest inValue = new WpfApp1.UTIL.loginRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputPassword = inputPassword;
            return ((WpfApp1.UTIL.ServicesPortType)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.UTIL.showProfileResponse WpfApp1.UTIL.ServicesPortType.showProfile(WpfApp1.UTIL.showProfileRequest request) {
            return base.Channel.showProfile(request);
        }
        
        public string[] showProfile(string inputPhoneNumber) {
            WpfApp1.UTIL.showProfileRequest inValue = new WpfApp1.UTIL.showProfileRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            WpfApp1.UTIL.showProfileResponse retVal = ((WpfApp1.UTIL.ServicesPortType)(this)).showProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.UTIL.showProfileResponse> WpfApp1.UTIL.ServicesPortType.showProfileAsync(WpfApp1.UTIL.showProfileRequest request) {
            return base.Channel.showProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.UTIL.showProfileResponse> showProfileAsync(string inputPhoneNumber) {
            WpfApp1.UTIL.showProfileRequest inValue = new WpfApp1.UTIL.showProfileRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            return ((WpfApp1.UTIL.ServicesPortType)(this)).showProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.UTIL.changePasswordResponse WpfApp1.UTIL.ServicesPortType.changePassword(WpfApp1.UTIL.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public int changePassword(string inputPhoneNumber, string inputTcNumber, string inputNewPassword) {
            WpfApp1.UTIL.changePasswordRequest inValue = new WpfApp1.UTIL.changePasswordRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputTcNumber = inputTcNumber;
            inValue.inputNewPassword = inputNewPassword;
            WpfApp1.UTIL.changePasswordResponse retVal = ((WpfApp1.UTIL.ServicesPortType)(this)).changePassword(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.UTIL.changePasswordResponse> WpfApp1.UTIL.ServicesPortType.changePasswordAsync(WpfApp1.UTIL.changePasswordRequest request) {
            return base.Channel.changePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.UTIL.changePasswordResponse> changePasswordAsync(string inputPhoneNumber, string inputTcNumber, string inputNewPassword) {
            WpfApp1.UTIL.changePasswordRequest inValue = new WpfApp1.UTIL.changePasswordRequest();
            inValue.inputPhoneNumber = inputPhoneNumber;
            inValue.inputTcNumber = inputTcNumber;
            inValue.inputNewPassword = inputNewPassword;
            return ((WpfApp1.UTIL.ServicesPortType)(this)).changePasswordAsync(inValue);
        }
    }
}
